name: Pull Request Checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to analyze"
        required: true
        default: "main"
      scan-type:
        description: "Type of scan to perform"
        required: true
        type: choice
        options:
          - quick
          - thorough
        default: "quick"

jobs:
  check-pr-type:
    runs-on: ubuntu-latest
    outputs:
      is_regular_pr: ${{ !startsWith(github.head_ref, 'release/v') }}
    steps:
      - run: echo "Determining PR type..."

  static-analysis:
    needs: check-pr-type
    # Run if it's a regular PR or manually triggered
    if: needs.check-pr-type.outputs.is_regular_pr == 'true' || github.event_name == 'workflow_dispatch'
    name: Static Analysis
    uses: ./.github/workflows/components/static-analysis/semgrep.yaml
    with:
      scan-type: ${{ github.event.inputs.scan-type || 'quick' }}
      rules: p/default
      severity: WARNING
      upload-artifact: true
    secrets:
      semgrep-token: ${{ secrets.SEMGREP_APP_TOKEN }}
