name: Pre-commit Checks
on:
  workflow_call:
    inputs:
      hooks:
        required: false
        type: string
        description: "Specific hooks to run, space separated"
        default: ""
      args:
        required: false
        type: string
        description: "Additional arguments for pre-commit run"
        default: ""

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit install-hooks

      - name: Load pre-commit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: |
          if [ -n "${{ inputs.hooks }}" ]; then
            pre-commit run --show-diff-on-failure --color=always \
              ${{ inputs.args }} \
              ${{ inputs.hooks }}
          else
            pre-commit run --show-diff-on-failure --color=always \
              ${{ inputs.args }} \
              --all-files
          fi