workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  #  - docs
  - coverage

build_image:
  stage: build
  tags:
    - build-image
  script:
    - export http_proxy=http://proxy-dmz.intel.com:912
    - export https_proxy=http://proxy-dmz.intel.com:912
    - docker build -t registry-icv.inn.intel.com/anomalib_dev/anomalib_development_env .
  only:
    refs:
      - merge_requests
    changes:
      - Dockerfile
      - requirements/requirements.txt
  except:
    - /^feature/

#pages:
#  image: registry-icv.inn.intel.com/anomalib_dev/anomalib_development_env
#  stage: docs
#  tags:
#    - docker
#  script:
#    - mkdir public
#    - cd docs
#    - pip install -r requirements.txt
#    - sphinx-build -b html source build
#    - cp -r ./build ../public
#  artifacts:
#    paths:
#      - public

coverage:
  image: registry-icv.inn.intel.com/anomalib_dev/anomalib_development_env
  stage: coverage
  tags:
    - docker
  before_script:
    - mkdir -p $HOME/.docker/
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"http://proxy-dmz.intel.com:912\", \"httpsProxy\": \"http://proxy-dmz.intel.com:912\",, \"ftpProxy\": \"http://proxy-dmz.intel.com:912\", \"noProxy\": \"$NO_PROXY\" } } }" > $HOME/.docker/config.json'
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"http://proxy-dmz.intel.com:912\", \"httpsProxy\": \"http://proxy-dmz.intel.com:912\", , \"ftpProxy\": \"http://proxy-dmz.intel.com:912\", \"noProxy\": \"$NO_PROXY\" } } }" '
  script:
    - nvidia-smi
    - tox
  timeout: 3h
  artifacts:
    reports:
      cobertura: .tox/coverage.xml
  except:
    - /^feature/
