data:
  class_path: anomalib.data.Visa
  init_args:
    root: ./datasets/visa
    category: capsules
    train_batch_size: 1
    eval_batch_size: 1
    num_workers: 4

model:
  class_path: anomalib.models.image.l2bt.lightning_model.L2BT
  init_args:
    lr: 1.0e-4
    image_size: 1036
    checkpoint_folder: ./checkpoints/checkpoints_visa
    class_name: capsules
    label: final_model
    epochs_no: 50
    batch_size: 4
    layers: [7, 11]
    load_pretrained: true

trainer:
  accelerator: auto
  devices: 1
  max_epochs: 1
