dataset:
  name: mvtec
  format: anomaly_dataset
  path: ./datasets/MVTec
  url: ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_anomaly_detection/mvtec_anomaly_detection.tar.xz
  task: segmentation
  category: carpet
  label_format: None
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
  train_batch_size: 32
  test_batch_size: 1
  num_workers: 36

transform:
  image_size: 256
  crop_size: 224
  grayscale: 0
  bilateral_filter:
    diameter: 9
    sigma_color: 75
    sigma_space: 75
    always_apply: 0
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  rotate_flip_p: 0.2
  gauss_noise_p: 0.001
  blur:
    motion_blur_p: 0.2
    median_blur:
      blur_limit: 3
      p: 0.1
    blur:
      blur_limit: 3
      p: 0.1
    p: 0.02
  shift_scale_rotate:
    shift_limit: 0.0625
    scale_limit: 0.2
    rotate_limit: 10
    p: 0.2
  geometric_transforms:
    optical_distortion_p: 0.3
    grid_distortion_p: 0.1
    affine_p: 0.3
    p: 0.1
  image_adjustments:
    clahe_clip_limit: 2
    p: 0.2
  image_compression:
    quality_lower: 55
    quality_upper: 99
    p: 0.2
  p: 0.0

model:
  name: patchcore
  backbone: wide_resnet50_2
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.001
  num_neighbors: 9
  metric: auc
  weight_file: weights/model.ckpt

project:
  seed: 0
  path: ./results
  log_images_to: [local]
  logger: false

optimization:
  compression:
    apply: false
  nncf:
    apply: false
    input_info:
      sample_size: null
    compression:
      algorithm: quantization
      initializer:
        range:
          num_init_samples: 256
    update_config:
      project:
        path: ./results_nncf
      init_weights: snapshot.ckpt
      hyperparameter_search:
        parameters:
          lr:
            min: 1e-4
            max: 1e-2

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  default_root_dir: null
  deterministic: true
  distributed_backend: null
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: 1
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 1
  max_steps: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
