algorithm: "bayes"
spec:
  maxCombo: 10
  metric: "image_F1Score"
  objective: "maximize"
parameters:
  data:
    class_path: anomalib.data.MVTec
    init_args:
      category: capsule
      image_size:
        type: discrete
        values: [128, 256]
  model:
    class_path: anomalib.models.Padim
    init_args:
      backbone:
        type: categorical
        values: ["resnet18", "wide_resnet50_2"]
