observation_budget: 10
method: bayes
metric:
  name: pixel_AUROC
  goal: maximize
parameters:
  data:
    class_path: anomalib.data.MVTec
    init_args:
      category: capsule
      image_size:
        values: [128, 256]
  model:
    class_path: anomalib.models.Padim
    init_args:
      backbone:
        values: [resnet18, wide_resnet50_2]
