# PR Title Check Workflow
#
# This reusable workflow validates PR titles to ensure they follow
# conventional commit format using Commitizen.
#
# Key Features:
# - Conventional commit validation for PR titles
# - Commitizen integration
# - Detailed error reporting
# - Configurable validation rules
#
# Process Stages:
# 1. Environment Setup:
#    - Python installation
#    - Commitizen installation
#
# 2. Title Analysis:
#    - PR title extraction
#    - Format compliance check
#
# 3. Validation Results:
#    - Error reporting
#    - Success confirmation
#    - Detailed feedback
#
# Required Inputs:
# - python-version: Python version for validation (default: "3.10")
#
# Example Usage:
# 1. Basic Validation:
#    jobs:
#      pr-title-check:
#        uses: ./.github/workflows/_reusable-pr-title-check.yaml
#
# 2. Custom Configuration:
#    jobs:
#      pr-title-check:
#        uses: ./.github/workflows/_reusable-pr-title-check.yaml
#        with:
#          python-version: "3.11"
#
# Note: Requires Commitizen configuration in pyproject.toml

name: Reusable PR Title Check

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version for validation"
        type: string
        default: "3.10"

permissions:
  contents: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Validating PR title: '$PR_TITLE'"

          if [ -z "$PR_TITLE" ]; then
            echo "::error::PR title is empty"
            exit 1
          fi

          # Create a temporary file to store the PR title for checking
          TEMP_TITLE_FILE=$(mktemp)
          # Ensure the temp file is cleaned up on exit
          trap 'rm -f "$TEMP_TITLE_FILE"' EXIT

          # Write the PR title to the temporary file
          echo "$PR_TITLE" > "$TEMP_TITLE_FILE"

          # Check the PR title using commitizen
          if ! cz check --commit-msg-file "$TEMP_TITLE_FILE"; then
            echo "::error::PR title does not follow conventional commit format"
            echo "::error::Title: $PR_TITLE"
            echo "::error::Please update your PR title to follow the conventional commit format"
            echo "::error::Examples:"
            echo "::error::  feat(data): add support for custom dataset formats"
            echo "::error::  fix(model): resolve memory leak in PatchCore training"
            echo "::error::  docs: update installation instructions"
            echo "::error::  chore(ci): update pre-commit hooks"
            exit 1
          fi

          echo "✅ PR title follows conventional commit format"
