name: Pre-merge Checks

on:
  push:
    branches: [development, master]
  pull_request:

jobs:
  Code-Quality-Checks:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Print PATH
        run: echo $PATH
      - run: tox
