name: Security Checks

on:
  pull_request: {}
  push:
    branches: ["main", "master"]

jobs:
  security-scan:
    name: Security Scanning
    uses: ./.github/workflows/semgrep-scan.yml
    with:
      rules: p/default
      severity: ERROR # Use environment variable instead of CLI flag
    secrets:
      semgrep-token: ${{ secrets.SEMGREP_APP_TOKEN }}
